= Sepia GFA Basic code

Internet is such a strange place. I've found by chance some lines of GFA Basic code I wrote something like 20 years ago.



Actually in the late 80s the French magazine ST Mag used to publish short GFA Basic programs written by the readers. These were called GFA Punch. They had to have at most 20 lines of code, and had to do something funny or useful. Some GFA Punch I had written were published. Someone kept a floppy disk of a bunch of GFA Punch that were published and made it available.link:http://www.chez.com/freddo/GfaBasic/GfaBasic.html[]



Now, among all these programs I've found some of my old GFA Punch. For me its like finding an old sepia picture in a box. It's weird. I've decided to post two of these programs just for archeological reason. There isn't any technological interest as the quality of the code is poor.



This one draw colored frames :





[source,ruby]
----
BOX 0,0,319,199
DIM b(1,3)
READ b(0,0),b(0,1),b(1,0),b(1,1),b(0,2),b(0,3),b(1,2),b(1,3)
DATA 30,30,40,21,1,1,1,1
COLOR 11
DO
  FOR t=0 TO 1
    ADD b(t,0),b(t,2)
    ADD b(t,1),b(t,3)
    IF POINT(b(t,0)+b(t,2),b(t,1))=1
      COLOR RANDOM(13)+2
      MUL b(t,2),-1
    ENDIF
    IF POINT(b(t,0),b(t,1)+b(t,3))=1
      COLOR RANDOM(13)+2
      MUL b(t,3),-1
    ENDIF
    LINE b(0,0),b(0,1),b(1,0),b(1,1)
  NEXT t
LOOP

----


This one draw a big ugly and slow scroll text :





[source,ruby]
----
Dim Big$(20)
For T%=1 To 20
  Print Mid$("SCROLLING, TRES LENT!",T%,1);Spc(10);"VEUILLEZ PATIENTER"
  For Y%=0 To 13          ! Monochrome: 13
    For X%=0 To 8
      If Point(X%,Y%)<>0
        Pcircle X%*10+5,Y%*10+5,5
      Endif
    Next X%
  Next Y%
  Get 9,0,71,80,Big$(T%)  ! A modifier aussi pour le monochrome
  Cls
Next T%
For T%=1 To 20
  Put 240,50,Big$(T%)
  Get 0,50,319,130,A$
  For R%=0 Downto -70
    Put R%,50,A$
  Next R%
Next T%

----
